export * from "./LandingPage/NavBar";
export * from "./LandingPage/Title/Title";
export * from "./LandingPage/CenteredText";
export * from './LandingPage/Figures/Figures';
export * from './LandingPage/Conversation/Conversation';
export * from '../components/LandingPage/CenteredText2/CenteredText2';
export * from './LandingPage/Footer/Footer';
export * from './DetailsPage/TitleDetails/TitleDetails';
export * from './WorksPage/Button/Button'
export * from './WorksPage/CV/CV';
export * from './WorksPage/CV/AppsData/AppData';
export * from './ContactPage/ContactDetails';
export * from './LandingPage/CenteredText2/Form/Form';